### ISSUE TITLE
Crash when loading

### ISSUE THREAD

**Issue by jbrown81** [sugeerth/BrainModulyzer#11]
Hi Sugeerth,
I'm trying to load a new dataset but get this crash on startup, using the latest version of modulyzer.

./RunProjectMain.py 
Files
Reading NII files.
Setting up the correlation table display.
Setting up main GUI.
Setting up Slice Views
Setting up the IsoSurfaces
Traceback (most recent call last):
  File "/Users/jessebrown/Desktop/BrainModulyzer/src/brain-vis/BrainViewer.py", line 130, in <module>
    ParcelationPlot = ParcelationPlotWindow(parcelation_filename, template_filename, correlationTable,selectedColor,colorTable, slice_views[0],slice_views[1],slice_views[2])
  File "/Users/jessebrown/Desktop/BrainModulyzer/src/brain-vis/VisitInterface/CreateParcelationPlot.py", line 129, in __init__
    self.RenderData()
  File "/Users/jessebrown/Desktop/BrainModulyzer/src/brain-vis/VisitInterface/CreateParcelationPlot.py", line 283, in RenderData
    self.SetRenderer()
  File "/Users/jessebrown/Desktop/BrainModulyzer/src/brain-vis/VisitInterface/CreateParcelationPlot.py", line 392, in SetRenderer
    self.addSpheres()
  File "/Users/jessebrown/Desktop/BrainModulyzer/src/brain-vis/VisitInterface/CreateParcelationPlot.py", line 673, in addSpheres
    x = float(self.Centroid[i][0])* self.PixX 
KeyError: 242

I've double checked that my parcellation file and matrix are correct. Any idea what this means?

The files I'm using are:
matrix_filename = 'connect_mat_263_thr100_w_regions_v2.csv'
parcelation_filename = 'all_vols_263.nii'
template_filename = 'MNI152_T1_2mm_brain.nii.gz'

The files are here:
https://www.dropbox.com/sh/71nsmk7mxux57ra/AACg7XvXr_NfCNbH4gTtveUwa?dl=0

Thanks!

**Comment by sugeerth** [comment]
Interesting! I believe there must be some hardcoded configurations in the code. I will get back to you on this.

**Comment by sugeerth** [comment]
Hi Jesse, 

I found the tool working fine in my end. May it might be the latest version. If you have a mac you can just use the conda installation and get it running. One of reason may be that you might have switched the parcellation and the template files ? This is the configuration that I have in my tool. 

matrix_filename = str(os.path.join(CURR,'connect_mat_263_thr100_w_regions_v2.csv'))
parcelation_filename = str(os.path.join(CURR, "all_vols_263.nii"))
template_filename = str(os.path.join(CURR, "MNI152_T1_2mm_brain.nii.gz"))


Attached are some of the screenshots. 
![screenshot 2017-05-06 15 21 22](https://cloud.githubusercontent.com/assets/4131680/25776315/fd62ccc0-326f-11e7-9fee-2e43e5cd5f41.jpg)
![screenshot 2017-05-06 15 19 37](https://cloud.githubusercontent.com/assets/4131680/25776317/00253dee-3270-11e7-877a-7042a0410fd8.jpg)

**Comment by sugeerth** [comment]
![screenshot 2017-05-06 15 25 02](https://cloud.githubusercontent.com/assets/4131680/25776328/3fda83ae-3270-11e7-85bf-4541f46b98a2.jpg)

**Comment by sugeerth** [comment]
Also, feel free to cite the manuscript in case you end up using BrainModulyzer:-). 
Feel free to post any more features/techniques (in issues) that you would maybe would like to see in the tool which might help your research.

**Comment by jbrown81** [comment]
Ah, I figured out the issue, I had extra values in the parcellation file that weren't in the expected range (1-263). Once I removed those values the program opened fine. I'm not sure why that file opened ok in your version but not in mine, I updated on May 3 so I should have the new version. In any case, glad it's working! Thanks.
