### ISSUE TITLE
updating the file paths to load data

### ISSUE THREAD

**Issue by katedamme** [sugeerth/BrainModulyzer#14]
**If I try to update files via the BrainViewerDataPaths.py** 

DataSetValue = 'Dataset2' # Change this to Dataset2 for other results

CURR =  path.abspath(path.join(__file__ ,"../..")) # going one directory up 
CURR = os.path.join(CURR, "SampleData/"+str(DataSetValue)+"/")

matrix_filename = str(os.path.join(CURR,'fc_mat_mean_hc_64.csv'))
parcelation_filename = str(os.path.join(CURR, "all_parcels.nii.gz"))
template_filename = str(os.path.join(CURR, "MNI152_T1_2mm_brain.nii.gz"))

**Then I get the following error:**

Traceback (most recent call last):
  File "BrainModulyzer/src/brain-vis/BrainViewer.py", line 130, in <module>
    ParcelationPlot = ParcelationPlotWindow(parcelation_filename, template_filename, correlationTable,selectedColor,colorTable, slice_views[0],slice_views[1],slice_views[2])
  File "BrainModulyzer/src/brain-vis/VisitInterface/CreateParcelationPlot.py", line 129, in __init__
    self.RenderData()
  File "BrainModulyzer/src/brain-vis/VisitInterface/CreateParcelationPlot.py", line 283, in RenderData
    self.SetRenderer()
  File "BrainModulyzer/src/brain-vis/VisitInterface/CreateParcelationPlot.py", line 392, in SetRenderer
    self.addSpheres()
  File "BrainModulyzer/src/brain-vis/VisitInterface/CreateParcelationPlot.py", line 673, in addSpheres
    x = float(self.Centroid[i][0])* self.PixX
KeyError: 102

**Comment by sugeerth** [comment]
Concerning the second example, if you try it again it should work. This is mostly for the centroid file, you can enter x,y,z positions in the centerData file

**Comment by katedamme** [comment]
So I've tried this multiple times, and it doesn't work launch, and gives the same error. There is no place in the BrainViewerDataPaths.py to specifiy a centroid coordinate file. Where would I find the centerData file specification to update the coordinates?

**Comment by sugeerth** [comment]
Currently, the tool automatically computes the centroid coordinate view for
you see the structure of the graph. I can go ahead and decouple and
unactive that feature so that you can better see the patterns without the
centroid view

**Comment by katedamme** [comment]
I'd like to have the centroid view, I just want to be able to run  the SampleData2, but ./RunProjectMain.py 
won't run if the BrainViewerDataPaths.py is set to Dataset2

**Comment by sugeerth** [comment]
Made some changes in the paths file

**Comment by katedamme** [comment]
Perfect! That did the trick! Thanks so much! I really love this tool, and the interface!
