### ISSUE TITLE
Still getting segmentation error

### ISSUE THREAD

**Issue by jersdeng** [sugeerth/BrainModulyzer#8]
I'm getting a segmentation error again when testing the newest version of Modulyzer on Ubuntu 14.04. I'm using the same dependencies that I used to get the old version working (e.g. vtk 7.1). Last time, commenting out the self.FinalRenderView() method in CreateVolumneRenderer.py allowed the program to move past the error, but it didn't help this time. Here's the output:

Files
Reading NII files.
Setting up the correlation table display.
Setting up main GUI.
Setting up Slice Views
Setting up the IsoSurfaces
libGL error: failed to load driver: swrast
ERROR: In /home/jdeng/projects/VTK/Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 597
vtkXOpenGLRenderWindow (0x3d79140): GLEW could not be initialized.

**Comment by sugeerth** [comment]
Sorry for the delay, I got caught with one of my presentations for an upcoming conference. I did get somewhere with regard to the conda packaging. Try running 

    conda config -add channels conda-forge anaconda allank asmeurer menpo

and then 

    conda install -c sugeerth brainmodulyzer_1=1.1.1
 
and let me know if you face any problems. If you do not have any problems installing then 
download the latest version of brainmodulyzer and run 

    modulyzerdir/src> RunProjectMain.py 

#Make sure that the system uses conda python

**Comment by jersdeng** [comment]
Thanks Sugeerth, I will have some time to test this today.

**Comment by jersdeng** [comment]
Installation went fine overall. I set up an environment and was able to conda install -c sugeerth brainm=1.0.1 although I did have to install pygraphviz first (conda install -c pdrops pygraphviz=1.2) or else it gave me this error:

**Comment by jersdeng** [comment]
Error: Dependency missing in current linux-64 channels:
  - brainm 1.0.1* -> pygraphviz

**Comment by sugeerth** [comment]
you may want to install 
https://anaconda.org/pdrops/pygraphviz

conda install -c pdrops pygraphviz=1.2

**Comment by jersdeng** [comment]
I cloned the latest version of the tool, changed to the src directory, and ran "python RunProjectMain.py". This was the output:

Reading NII files.
Setting up the correlation table display.
Setting up main GUI.
Setting up Slice Views
Setting up the IsoSurfaces
libGL error: failed to load driver: swrast
ERROR: In ../Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 533
vtkXOpenGLRenderWindow (0x288e420): GLEW could not be initialized.

Segmentation fault (core dumped)

**Comment by sugeerth** [comment]
you can also do pip if it does not work

**Comment by sugeerth** [comment]
Hmm seems like we might have the same graphics driver error.  I am currently looking at some known solutions that might fix

**Comment by jersdeng** [comment]
Sounds good. Besides that, is there any reason why the pygraphviz dependency does not install along with all of the other dependencies? Seems like everything else is wrapped up nicely except for pygraphviz.

**Comment by sugeerth** [comment]
https://www.codeweavers.com/support/wiki/Diag/MissingLibGL

one option might be to completely remove nvidia drivers and install new nvidia drivers and try them.

**Comment by sugeerth** [comment]
But again this is only at your own risk. 
The pygraphviz should have been installed. Did you add 
    conda config --add channels  pdrops

**Comment by jersdeng** [comment]
Hmm I might have forgotten to do that. I will try to do a fresh installation again after adding that channel.

I have gotten the same libGL message in the past when launching Matlab, but Matlab always launches in spite of it, so I'm wondering whether the libGL issue is the actual problem. What about this error?
ERROR: In ../Rendering/OpenGL2/vtkOpenGLRenderWindow.cxx, line 533
vtkXOpenGLRenderWindow (0x288e420): GLEW could not be initialized.

**Comment by jersdeng** [comment]
Forgot to mention, the above was tested on Ubuntu 14.04. I also tested it on Mac OS X Yosemite and did not run into any problems. 
<img width="2344" alt="screen shot 2016-09-07 at 3 30 31 pm" src="https://cloud.githubusercontent.com/assets/12741669/18330883/0c5a5b6c-7510-11e6-830d-a19a808aaf1c.png">

I can try testing the program on another Ubuntu machine if the graphics driver error is just some peculiarity with the machine I was testing on.

**Comment by jersdeng** [comment]
Although is there supposed to be a correlation table popup also?

**Comment by sugeerth** [comment]
Seems like a problem either in libgl installation or some dependency with nvidia. I remember this was tricky when I had nvidia earlier.
 
I tried installing from scratch in linux and mac. It seems to work fine.

**Comment by sugeerth** [comment]
Yes you can turn off/on the correlation table based on brainviewerdatapaths.py file.

**Comment by jersdeng** [comment]
Ah thanks, I see the table now. I will give the Linux installation another shot.

**Comment by sugeerth** [comment]
ok cool, that it works in Yosemite. I will do bit more testing and hopefully by the end of next week (the IP would also come through), we can do a tool release so that all users can use it with less ease. 

Some other stuff that needs work is loading datasets and taking snapshots of the viz. I will work on those features over the weekend.

**Comment by jersdeng** [comment]
Happy to report that I got it working on a different Linux machine running Ubuntu 14.04.3. Installation was quick and painless. Thanks for packaging it. It makes a big difference.
<img width="2560" alt="screen shot 2016-09-07 at 4 29 35 pm" src="https://cloud.githubusercontent.com/assets/12741669/18332047/4f98feda-7518-11e6-84d3-8ba1c8470325.png">

**Comment by sugeerth** [comment]
interesting that the vtk module is still not working. I will look for any other good installation procedure for installing libGL
